# Generated by Django 5.2.1 on 2025-05-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_bookmark_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
