# Generated by Django 5.2.1 on 2025-05-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_bookmark_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='slug',
            field=models.SlugField(blank=True, default='temp-slug', unique=True),
            preserve_default=False,
        ),
    ]
