# Generated by Django 5.2.1 on 2025-05-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_bookmark_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
