# Generated by Django 5.2.1 on 2025-05-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_file_bookmark_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
