# Generated by Django 5.2.1 on 2025-05-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_alter_file_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='slug',
        ),
    ]
