# Generated by Django 5.2.1 on 2025-05-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
